---
title: "pandas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Tidying Data

```{r}
library(reticulate)
library(tidyverse)
library(ggplot2)


tbl <- data.frame(stringsAsFactors=FALSE,
    Religion = c("Agnostic", "Atheist", "Buddhist", "Catholic", "Others"),
      "0K-20K" = c(61, 39, 48, 1035, 2040),
     "20K-40K" = c(141, 89, 64, 1402, 2660),
     "40K-75K" = c(213, 105, 91, 1754, 3053)
    )

# tidying the data
tbl_longer <- tbl %>% 
    pivot_longer(contains("K"), names_to = "Income", values_to = "Frequency")
tbl_longer

# stacked bar graph
tbl_longer %>% 
    ggplot(aes(Religion, Frequency, fill = Income)) +
    geom_col(position = "stack")

# faceted bar graph
tbl_longer %>% 
    ggplot(aes(Religion, Frequency)) +
    geom_col() +
    facet_wrap(~Income)

# coming back, pivoting the data
tbl_wider <- tbl_longer %>% 
    pivot_wider(names_from = Income, values_from = Frequency)
tbl_wider
```


# Now the same in Pandas

```{python}
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

# bringing the data from R environment
df = r.tbl
df

# tidying the data in Pandas
df_melt = df.melt(var_name="Income", value_name="Frequency", id_vars="Religion", 
                  value_vars=["X0K.20K", "X20K.40K", "X40K.75K"])
df_melt

# seaborn does not have stacked bar plot
sns.barplot(data=df_melt, x="Religion", y="Frequency", hue="Income")
plt.show()

# we can do it with pandas by it is hard to understand why the sintax work
df.plot.bar(x="Religion", stacked=True)
plt.show()

# coming back, pivoting the data
df_pivot = df_melt.pivot(index="Religion", columns="Income", values="Frequency")
df_pivot
```


# Reference
https://blog.zenggyu.com/en/post/2019-01-02/switching-between-tidyverse-and-pandas-for-tabular-data-wrangling-tidying-data/
