---
title: "Tune Tidymodels"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## BASIC GRID SEARCH
```{r}
library(tidyverse)
library(tidymodels)

library(mlbench)
data("Ionosphere")

Ionosphere %>% glimpse()

Ionosphere %>% count(V1)
Ionosphere %>% count(V2)
Ionosphere %>% count(Class)
```

```{r}
glm(Class ~ ., data = Ionosphere, family = binomial)

glm(Class ~ . - V2, data = Ionosphere, family = binomial)

Ionosphere <- Ionosphere %>% select(-V2)
```

## Inputs for the Search
```{r}
svm_mod <- svm_rbf(cost = tune(), rbf_sigma = tune()) %>% 
    set_mode("classification") %>% 
    set_engine("kernlab")

iono_rec <- recipe(Class ~ ., data = Ionosphere) %>% 
    # In case V1 has a single value sampled
    step_zv(all_predictors()) %>% 
    # convert it to a dummy variable
    step_dummy(V1) %>% 
    # Scale it the same as the others
    step_range(matches("V1_"))

set.seed(4943)
iono_rs <- bootstraps(Ionosphere, times = 30)
```


## Optional Inputs
```{r}
roc_vals <- metric_set(roc_auc)

library(tune)
ctrl <- control_grid(verbose = FALSE)
```


## Executing the Grid Using a Formula
```{r}
set.seed(35)

grid_form <- tune_grid(
    Class ~ .,
    model = svm_mod,
    resamples = iono_rs,
    metrics = roc_vals,
    control = ctrl
    )

grid_form

grid_form %>% 
    select(.metrics) %>% 
    slice(1) %>% 
    pull(1)
```




