---
title: "Lags and Mving Means"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

df <- expand.grid(site = factor(seq(10)),
                  year = 2000:2004,
                  day = 1:50)
# use Poisson to make math easy to check moving means of temperature
df$temp = rpois(dim(df)[1], 5) 
# Assume rains 33% of the days and averages 5 mm each time but highly variable
df$precip = rbinom(dim(df)[1], 1, 1/3) * rlnorm(dim(df)[1], log(5), 1)
```

# Moving mean for that day and previous days
```{r}
df %>% 
    group_by(site, year) %>% 
    arrange(site, year, day) %>% 
    mutate(temp_5 = zoo::rollmean(x = temp, 5, align = "right", fill = NA)) %>% 
    ungroup() %>% 
    View()
```

# Moving mean for the previous days not including the current day (e.g. 5 represents the mean of the 5 previous days)
```{r}
df %>% 
    mutate(temp_lag1 = lag(temp, 1)) %>% 
    mutate(temp_5_previous = zoo::rollapply(data = temp_lag1,
                                            width = 5,
                                            FUN = mean,
                                            align = "right",
                                            fill = NA,
                                            na.rm = T)) %>% 
    View()
```

# Rolling sum of the precipitation for the previous 30 days, including the current day
```{r}
df %>% 
    mutate(precip_30 = zoo::rollsum(x = precip, 30, align = "right", fill = NA)) %>% 
    View()
```


# Putting it all together at the same pipeline

```{r}
df %>% 
    group_by(site, year) %>% 
    arrange(site, year, day) %>% 
    mutate(temp_5 = zoo::rollsum(x = temp, 5, align = "right", fill = NA),
           temp_2_previous = rollapply(data = lag(temp),
                                       width = 2, 
                                       FUN = mean,
                                       align = "right",
                                       fill = NA,
                                       na.rm = T),
           precip_30 = rollsum(x = precip, 30, align = "right", fill = NA)) %>% 
    View()
```


